// constants/officials.ts

export type Officials = {
    id: string;
    name: string;
    title: string; // professor, instructor, dean
    position: string; // chair, director, chief, head, administrative staff
    program: string; // e.g., Master of Science in Information Technology
};

// Institute of Open & Distance Education – Graduate Program Chairs (from OUS)
export const OFFICIALS: Officials[] = [

    {
        id: 'gs-claudio',
        name: 'Sanjay P. Claudio, DPA',
        title: 'Professor VI',
        position: 'Program Chair',
        program: 'Master in Public Administration',
    },
    {
        id: 'gs-cresencio',
        name: 'Marion A. Cresencio, EdD',
        title: 'Professor IV',
        position: 'Program Chair',
        program: 'Master of Arts in Education',
    },
    {
        id: 'gs-manda',
        name: 'Aimee Rose A. Manda, PhD',
        title: 'Associate Professor I',
        position: 'Program Chair',
        program: 'Doctor of Philosophy in Psychology',
    },
    {
        id: 'gs-alagaran',
        name: 'Jose Reuben Q. Alagaran II, PhD',
        title: 'Professor II',
        position: 'Program Chair',
        program: 'PhD in Communication',
    },
    {
        id: 'gs-paz',
        name: 'Rafael Michael O. Paz, PhD',
        title: 'Professor IV',
        position: 'Program Chair',
        program: 'Doctor of Philosophy in English Language Studies',
    },
    {
        id: 'gs-pena1',
        name: 'Romeo P. Peña, PhD',
        title: 'Professor VI',
        position: 'Program Chair',
        program: 'Master of Arts in Filipino',
    },
    {
        id: 'gs-pena2',
        name: 'Romeo P. Peña, PhD',
        title: 'Professor VI',
        position: 'Program Chair',
        program: 'Doctor of Philosophy in Filipino',
    },
    {
        id: 'gs-mayrena',
        name: 'Marissa L. Mayrena, PhD',
        title: 'Associate Professor IV',
        position: 'Program Chair',
        program: 'Master of Arts in English Language Studies',
    },
    {
        id: 'gs-usona',
        name: 'Laurence P. Usona, MS',
        title: 'Associate Professor V',
        position: 'Program Chair',
        program: 'Master in Applied Statistics',
    },
    {
        id: 'gs-sebastian',
        name: 'Raul Roland Sebastian, DPA',
        title: 'Professor VI',
        position: 'Program Chair',
        program: 'Master of Arts in Philippine Studies',
    },
    {
        id: 'gs-santos',
        name: 'Geraldine F. Santos, PhD',
        title: 'Associate Professor IV',
        position: 'Program Chair',
        program: 'Master of Arts in Psychology',
    },
    {
        id: 'gs-ballano',
        name: 'Vivencio O. Ballano, PhD',
        title: 'Associate Professor V',
        position: 'Program Chair',
        program: 'Master of Arts in Sociology',
    },
    {
        id: 'gs-alvarez',
        name: 'Lourdes V. Alvarez, PhD',
        title: 'Professor VI',
        position: 'Program Chair',
        program: 'Master of Science in Biology',
    },
    {
        id: 'gs-magsumbol',
        name: 'Jo‑Ann V. Magsumbol',
        title: 'Associate Professor III',
        position: 'Program Chair',
        program: 'Master of Science in Electronics Engineering',
    },
    {
        id: 'gs-mojica',
        name: 'Edison E. Mojica, PhD',
        title: 'Professor II',
        position: 'Program Chair',
        program: 'Master of Science in Electrical Engineering',
    },
    {
        id: 'gs-cornell',
        name: 'Daryl Ace V. Cornell, PhD',
        title: 'Professor VI',
        position: 'Program Chair',
        program: 'Master of Science in International Tourism and Hospitality Management',
    },
    {
        id: 'gs-torres',
        name: 'Maria Cecilia B. Torres, PhD',
        title: 'Associate Professor III',
        position: 'Program Chair',
        program: 'Master of Science in Nutrition and Dietetics',
    },
    {
        id: 'gs-dizon',
        name: 'Ricardo L. Dizon, PhD',
        title: 'Professor VI',
        position: 'Program Chair',
        program: 'Master of Science in Economics',
    },
    {
        id: 'gs-tana1',
        name: 'Kenneth Bryan M. Tana, MSCM',
        title: 'Associate Professor V',
        position: 'Program Chair',
        program: 'Master of Science in Civil Engineering',
    },
    {
        id: 'gs-tana2',
        name: 'Kenneth Bryan M. Tana, MSCM',
        title: 'Associate Professor V',
        position: 'Program Chair',
        program: 'Professional Science Masters in Railway Engineering Management',
    },
    {
        id: 'gs-de-la-cruz',
        name: 'Arvin R. De la Cruz, PCpE, PhD',
        title: 'Professor I',
        position: 'Program Chair',
        program: 'Master of Science in Computer Engineering',
    },
    {
        id: 'gs-ermita1',
        name: 'Philip P. Ermita, PhD, ASEAN Engr.',
        title: 'Professor I',
        position: 'Program Chair',
        program: 'Master of Science in Industrial Engineering',
    },
    {
        id: 'gs-ermita2',
        name: 'Philip P. Ermita, PhD, ASEAN Engr.',
        title: 'Professor I',
        position: 'Director',
        program: 'Graduate Diploma in Project Management',
    },
    {
        id: 'gs-comendador',
        name: 'Benilda Eleonor V. Comendador, DIT',
        title: 'Professor VI',
        position: 'Program Chair',
        program: 'Master of Science in Information Technology',
    },
    {
        id: 'gs-fajardo',
        name: 'Kim Bernard G. Fajardo, MC',
        title: 'Associate Professor IV',
        position: 'Program Chair',
        program: 'Master of Arts in Communication',
    },
    {
        id: 'iode-gpc-bernanbe',
        name: 'Guillermo O. Bernabe, DEM',
        title: 'Professor',
        position: 'Program Chair',
        program: 'Master of Science in Construction Management',
    },
    {
        id: 'iode-gpc-lacerna',
        name: 'Rudolf Anthony A. Lacerna, DEM, DR&DM',
        title: 'Associate Professor',
        position: 'Program Chair',
        program: 'Doctor of Philosophy in Education Management',
    },
    {
        id: 'iode-gpc-ortiz',
        name: 'Marianne C. Ortiz, MAF',
        title: 'Associate Professor',
        position: 'Academic Program Head',
        program: 'Master of Arts in Education Management (and DEM)',
    },
    {
        id: 'iode-gpc-andres',
        name: 'Ginno L. Andres, D.Eng.',
        title: 'Professor',
        position: 'Program Chair',
        program: 'Doctor in Engineering Management',
    },
    {
        id: 'iode-gpc-claudio',
        name: 'Sanjay P. Claudio, DPA',
        title: 'Professor',
        position: 'Program Chair',
        program: 'Doctor in Public Administration',
    },
    {
        id: 'iode-gpc-reyes1',
        name: 'Jerielyn V. Reyes, DBA',
        title: 'Associate Professor',
        position: 'Program Chair',
        program: 'Master in Business Administration',
    },
    {
        id: 'iode-gpc-reyes2',
        name: 'Jerielyn V. Reyes, DBA',
        title: 'Associate Professor',
        position: 'Program Chair',
        program: 'Doctor in Business Administration',
    },
    {
        id: 'iode-gpc-dizon',
        name: 'Rosemariebeth R. Dizon, DEM',
        title: 'Professor',
        position: 'Program Chair',
        program: 'Master in Education Management',
    },
    {
        id: 'iode-gpc-mantillas',
        name: 'Christopher C. Mantillas, PhD',
        title: 'Professor',
        position: 'Program Chair',
        program: 'Master in Public Administration',
    },
    {
        id: 'iode-gpc-comendador',
        name: 'Benilda Eleanor V. Comendador, DIT',
        title: 'Professor',
        position: 'Program Chair',
        program: 'Master in Information Technology',
    },
];
